// <auto-generated />
using System;
using MeshVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeshVault.Data.Migrations
{
    [DbContext(typeof(MeshVaultDbContext))]
    [Migration("20260820195915_ModelSnapshots")]
    partial class ModelSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CollectionModelEntry", b =>
                {
                    b.Property<int>("CollectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionsId", "ModelsId");

                    b.HasIndex("ModelsId");

                    b.ToTable("CollectionModelEntry");
                });

            modelBuilder.Entity("MeshVault.Core.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("MeshVault.Core.Models.Designer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("MeshVault.Core.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowOrganize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastScannedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DesignerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FileModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("License")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SnapshotUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSite")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThumbnailFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DesignerId");

                    b.HasIndex("Name");

                    b.HasIndex("SourceSite");

                    b.HasIndex("LibraryId", "RelativePath")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelEntryId");

                    b.HasIndex("UserId", "ModelEntryId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SizeX")
                        .HasColumnType("REAL");

                    b.Property<float?>("SizeY")
                        .HasColumnType("REAL");

                    b.Property<float?>("SizeZ")
                        .HasColumnType("REAL");

                    b.Property<int>("ThumbnailState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TriangleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("ModelEntryId", "RelativePath")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MeshVault.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ModelEntryTag", b =>
                {
                    b.Property<int>("ModelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModelsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ModelEntryTag");
                });

            modelBuilder.Entity("CollectionModelEntry", b =>
                {
                    b.HasOne("MeshVault.Core.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeshVault.Core.Models.ModelEntry", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelEntry", b =>
                {
                    b.HasOne("MeshVault.Core.Models.Designer", "Designer")
                        .WithMany("Models")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MeshVault.Core.Models.Library", "Library")
                        .WithMany("Models")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designer");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelFavorite", b =>
                {
                    b.HasOne("MeshVault.Core.Models.ModelEntry", "ModelEntry")
                        .WithMany("Favorites")
                        .HasForeignKey("ModelEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelEntry");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelFile", b =>
                {
                    b.HasOne("MeshVault.Core.Models.ModelEntry", "ModelEntry")
                        .WithMany("Files")
                        .HasForeignKey("ModelEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelEntry");
                });

            modelBuilder.Entity("ModelEntryTag", b =>
                {
                    b.HasOne("MeshVault.Core.Models.ModelEntry", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeshVault.Core.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshVault.Core.Models.Designer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("MeshVault.Core.Models.Library", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("MeshVault.Core.Models.ModelEntry", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
